# ini adalah komentar
# SINTAKSIS / BARIS KODE DALAM PYTHON
# VARIABEL DALAM PYTHON
# VARIABEL ADALAH SEBUAH NAMA ATAU KARAKTER YANG DIDEFINISIKAN UNTUK MENAMPUNG DATA

# JENIS JENIS OPERATOR 
# OPERATOR ADALAH SIMBOL YANG DIGUNAKAN UNTUK MELAKUKAN OPERASI TENTENTU
#1 OPERASI ARITMATIKA
# + = PENJUMLAHAN
# - = PENGURANGAN
# * = PERKALIAN
# / = PEMBAGIAN 
# % = SISA HASIL BAGI
# **= PERPANGKATAN |SEMUA INI OPERATOR

#2 OPERASI LOGIKA ADA 3
# a. LOGIKA AND
# b. LOGIKA OR
# c. LOGIKA NEGASI (net)

#3 OPERASI PEMBANDING | DIGUNAKAN UNTUK MEMBANDINGKAN SUATU NILAI PADA TIAP OPERATOR TERTENTU
# LAMBANG OPERATOR
# == = SAMA DENGAN
# != = TIDAK SAMA DENGAN
# >  = LEBIH BESAR 
# <  = LEBIH KECIL

# Contoh Operasi Aritmatika
#a = 5
#b = 6 
#print("a+b= ", a=b)



# Contoh Operasi Pembanding
#bil1 = float(input("Masukkan Bilangan Pertama: "))
#bil2 = float(input("Masukkan Bilangan Kedua: "))
#if bil1>bil2:
#    print(f"{bil1} lebih besar {bil2}")
#elif bil1 < bil2:
#    print(f"{bil1} lebih kecil dari {bil2}")
#else:
#    print(f"{bil1} sama dengan {bil2}")

# PERULANGAN DALAM BAHASA PEMROGRAMAN ADALAH PERINTAH ATAU MEMBERIKAN PERINTAH KEPADA KOMPUTR UNTUK MELAKUKAN SESUATU SECARA BERULAN ULANG 
# PERULANGAN SENDIRI DIBAGI MENJADI 2
# 1. FOR (COUNTED LOOP) PERULANGAN YANG TERHITUNG
# 2. WHILE (UNCOUNTED LOOP) PERULANGAN YANG TAK TERHITUNG

#LIST ADALAH STRUKTUR DATA YANG MAMPU MENYIMPAN LEBIH DARI 1 DATAl